package com.sdp.pos.constant;

public enum PermissionEnum {
    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,
    PRODUCT_VIEW,
    PRODUCT_ADJUST_STOCK,
    PRODUCT_ADJUST_PRICE,

    PRODUCT_CATEGORY_CREATE,
    PRODUCT_CATEGORY_UPDATE,
    PRODUCT_CATEGORY_DELETE,
    PRODUCT_CATEGORY_VIEW,

    SUPPLIER_CREATE,
    SUPPLIER_UPDATE,
    SUPPLIER_DELETE,
    SUPPLIER_VIEW,

    USER_VIEW,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE

}
